[features]
seeds = false
skip-lint = false
[programs.localnet]
user_input = "8soeHxfXiasRH4FTRAD3D5JoxRcxHGo4xqK2E5GCHMHi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/home/coffee_is_bitter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
